version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb:latest
    ports:
      - "8080:8080"

  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - garnetdata:/data

volumes:
  ravendb_data:
  garnetdata: